version: '3.7'

services:
    flask:
        build: ./app/
        ports:
            - 5000:5000
        networks:
            - mySQL_db
    
    ma-bdd.com:
        image: mysql:8.0.26
        container_name: some_mysql1
        restart: unless-stopped
        environment: 
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db-init/:/docker-entrypoint-initdb.d
        networks:
            - mySQL_db

    adminer-pour-ma-bdd:
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
            - 8000:8080
        depends_on:
            - ma-bdd.com
        networks:
            - mySQL_db

networks:
    mySQL_db: